export const siteConfig = {
  name: "Fraga Technology",
  shortName: "Fraga",
  description:
    "We Build the Future. Fraga Technology delivers expert web development, mobile app development, SEO services, digital marketing, and graphic design solutions for businesses worldwide.",
  url: process.env.NEXT_PUBLIC_SITE_URL || "https://fragatechnology.com",
  ogImage: "/api/og",
  author: "Fraga Technology",
  email: "contact@fragatechnology.com",
  emailAlt: "fragatechnology@gmail.com",
  phone: "+91 9235000195",
  address: "F.F.D.C Kannauj, India",
  social: {
    linkedin: "https://linkedin.com/company/fragatechnology",
    twitter: "https://twitter.com/fragatechnology",
    instagram: "https://instagram.com/fragatechnology",
    facebook: "https://facebook.com/fragatechnology",
  },
  keywords: [
    "website development company",
    "mobile app development company",
    "web development services",
    "app development company",
    "startup website development",
    "company website development",
    "SEO services",
    "digital marketing agency",
    "graphic design services",
    "social media marketing",
    "Meta Ads management",
    "Google Ads management",
    "web development India",
    "app development USA",
    "SEO company UK",
    "digital marketing Canada",
    "website development Australia",
    "web development UAE",
  ],
  services: [
    { name: "Website Development", slug: "website-development" },
    { name: "Mobile App Development", slug: "mobile-app-development" },
    { name: "SEO Services", slug: "seo-services" },
    { name: "Meta Ads Management", slug: "meta-ads" },
    { name: "Google Ads Management", slug: "google-ads" },
    { name: "Graphics Design", slug: "graphics-design" },
    { name: "Social Media Marketing", slug: "social-media-marketing" },
  ],
  targetCountries: [
    "India",
    "USA",
    "UK",
    "Canada",
    "Australia",
    "UAE",
  ],
  targetCities: [
    "Delhi",
    "Bangalore",
    "Mumbai",
    "Hyderabad",
    "Pune",
    "San Francisco",
    "New York",
    "Austin",
    "Los Angeles",
    "Miami",
    "Toronto",
    "Vancouver",
    "Calgary",
    "Montreal",
    "London",
    "Manchester",
    "Birmingham",
    "Leeds",
    "Sydney",
    "Melbourne",
    "Brisbane",
    "Perth",
    "Dubai",
    "Abu Dhabi",
  ],
  targetIndustries: [
    "Real Estate Companies",
    "Law Firms",
    "Hospitals & Clinics",
    "SaaS Startups",
    "E-commerce Brands",
    "Marketing Agencies",
    "Construction Companies",
    "Insurance Companies",
    "Luxury Brands",
  ],
} as const

export type SiteConfig = typeof siteConfig
